Add deps detection bit

diff --git a/ptouch/local/bin/foomatic-rip b/ptouch/local/bin/foomatic-rip
--- a/ptouch/local/bin/foomatic-rip
+++ b/ptouch/local/bin/foomatic-rip
@@ -1,4 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+[ -e "$HOME/.bash/lib" ] &&
+  . "$HOME/.bash/lib"
 
 ptouch_usage() {
   echo '
@@ -52,6 +55,20 @@ Options:
 -U username             Specify the username to use for authentication
 '
 }
+
+deps=(ptouch-print)
+for script in "${deps[@]}"; do
+  if ! exists_exe "$script" &>/dev/null; then
+    echo "ERROR: Failed to find $script..."
+    echo
+    echo "INFO: Install this dependency via "
+    # TODO(JEFF): OS detection for archlinux && derived
+    # See terminfo/install.sh
+    echo "pamac ptouch-print"
+    echo
+    continue
+  fi
+done
 
 if ptouch-print --text $1; then
   true
