Begin fleshing out implementation

diff --git a/subl/local/bin/subl b/subl/local/bin/subl
--- a/subl/local/bin/subl
+++ b/subl/local/bin/subl
@@ -1,28 +1,41 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # subl:jeff
 #
 # Find And execute the best Visual text editor I am to likely have running
 # at the moment (depending on the operating system and all!)
 #
-# TODO(jeff): Add branching based on existing EDITOR, VISUAL environments that
-# we can glean
-NOM_DEBUG=0
 
-if [[ -n "$NOM_DEBUG" && $NOM_DEBUG -gt 0 ]]; then
+if [[ -n "$DEBUG" && "$DEBUG" -gt 0 ]]; then
   echo "$0: $@"
 fi
 
-# STUB(jeff): Need to flesh this implementation out. Surely, the branch code
-# as-is does not even work!
-if [[ -x "$(command -v flatpak)" && $(flatpak info com.sublimetext.three) = 0 ]]; then
-  flatpak run --branch=stable --arch=x86_64 --command=subl --file-forwarding com.sublimetext.three @@ "$@" @@
-elif [[ -x "$(command -v pulsar)" ]]; then
-  pulsar "$@"
-elif [[ -x "$(command -v atom)" ]]; then
-  atom "$@"
-elif [[ -x "$(command -v vim)" ]]; then
-  vim "$@"
-fi
+# TODO(jeff): Need to flesh this implementation out; cleanup the branching
+# model -- instead of only checking for the existance of various editor
+# commands, perhaps we ought to take into consideration what the pre-existing
+# EDITOR and VISUAL environment is setup as and try to use this as our primary
+# check?
 
-exit $?
+# fallback_editor(args = optional)
+fallback_editor() {
+  ARGS="$@"
+
+  if [[ -x "$(command -v flatpak)" && $(flatpak info com.sublimetext.three) = 0 ]]; then
+    flatpak run --branch=stable --arch=x86_64 --command=subl --file-forwarding com.sublimetext.three @@ "${ARGS[@]}" @@
+  elif [[ -x "$(command -v code-oss)" ]]; then
+    code-oss "${ARGS[@]}"
+  elif [[ -x "$(command -v code)" ]]; then
+    code "${ARGS[@]}"
+  elif [[ -x "$(command -v pulsar)" ]]; then
+    pulsar "${ARGS[@]}"
+  elif [[ -x "$(command -v atom)" ]]; then
+    atom "${ARGS[@]}"
+  elif [[ -x "$(command -v vim)" ]]; then
+    vim "${ARGS[@]}"
+  fi
+}
+
+fallback_editor "$@"
+
+exit "$?"
+
